version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=user-service:7000
      - SESSION_SECRET=your-super-secret-key-change-in-production
    command: nodemon ./bin/www
    volumes:
      - ./src/frontend:/app
    depends_on:
      - user-service

  user-service:
    build:
      context: ./src/user-service
    ports:
      - "7000"
    environment:
      - MONGODB_URL=mongodb://mongo-service:27017/microservices_development
    command: nodemon server.js
    volumes:
      - ./src/user-service:/app
    depends_on:
      - mongo-service

  mongo-service:
    build:
      context: ./src/mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
