apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: narralabs/frontend
      context: src/frontend
    - image: narralabs/user-service
      context: src/user-service
    - image: narralabs/chat-service
      context: src/chat-service
    - image: narralabs/llama-service
      context: src/llama-service
manifests:
  kustomize:
    paths:
      - "./k8s-manifests"
