apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: frontend
      context: src/frontend
    - image: user-service
      context: src/user-service
    - image: mongo-service
      context: src/mongo-service
manifests:
  kustomize:
    paths:
      - "./k8s-manifests"
