apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: frontend
      context: src/frontend
      sync:
        manual:
          - src: '**'
            dest: /app
    - image: userservice
      context: src/userservice
      sync:
        manual:
          - src: '**'
            dest: /app
    - image: mongoservice
      context: src/mongoservice