apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-k8s-pod
  template:
    metadata:
      labels:
        app: frontend-k8s-pod
    spec:
      # nodeSelector:
      #   role: worker
      containers:
        - name: frontend
          image: narralabs/frontend
          ports:
            - containerPort: 3000
          env:
            - name: USER_SERVICE_URL
              value: user-service-k8s-service:7000
            - name: SESSION_SECRET
              value: your-super-secret-key-change-in-production
            - name: CHAT_SERVICE_URL
              value: chat-service-k8s-service:50051
            - name: CART_SERVICE_URL
              value: cart-service-k8s-service:7002
          command: ["nodemon", "./bin/www"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-service
spec:
  selector:
    app: frontend-k8s-pod
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer