apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 20Gi